### ISSUE TITLE
[OB2][Berlin] - Server error for Initiation Request with debtorAccount in bban/pan attribute

### ISSUE THREAD

**Issue by malshaniS** [wso2/reference-implementation-nextgenpsd2#165]
**Description:**
Getting 500 server error with below response when making bulk payment initiation request with debtorAccount in bban and pan attribute. 

<img width="909" alt="Screenshot 2020-08-14 at 19 39 18" src="https://user-images.githubusercontent.com/40388545/90258223-d97afa80-de65-11ea-9b96-798970e03040.png">

Observed the below error log in AM for bban type debtorAccount.

`TID: [-1234] [api/openbanking/consent-mgt] [2020-08-14 16:55:00,150] [71e266f4-8e00-4b0f-bbe2-67f09dd992fa] ERROR {com.wso2.finance.open.banking.common.consent.mgt.endpoint.BerlinErrorGenerator} - ERROR com.wso2.finance.open.banking.common.exception.InvalidPayloadException: bban for Debtor Account should be equal for all payments
	at com.wso2.finance.open.banking.berlin.consent.mgt.endpoint.util.PaymentEndpointValidation.validatePayload(PaymentEndpointValidation.java:129)
	at com.wso2.finance.open.banking.berlin.consent.mgt.endpoint.impl.BG130PaymentsApiServiceImpl.postPaymentConsent(BG130PaymentsApiServiceImpl.java:126)
	at com.wso2.finance.open.banking.consent.mgt.endpoint.berlin130.payments.PaymentsApi.initiatePayment(PaymentsApi.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:94)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

Observed the below error log in AM for pan type debtorAccount.

`TID: [-1234] [] [2020-08-14 19:02:56,779]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - STATUS = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = JSONObject["iban"] not found.`

Even-though it gives an error saying "bban for Debtor Account should be equal for all payments" the payload contains the same debtor account.
Following is the Sample Request:
<img width="1154" alt="Screenshot 2020-08-14 at 19 39 52" src="https://user-images.githubusercontent.com/40388545/90258271-ee578e00-de65-11ea-81da-eef490a6116c.png">

@Note: The AccountReferenceType configuration in open-banking.xml is set to corresponding type {bban / pan}.

**Suggested Labels:**
Priority/High, Severity/Critical

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Set the AccountReferenceType config to bban.
2. Send bulk payment initiation request as below.

> POST	https://ob-stet:8243/xs2a/v1/bulk-payments/sepa-credit-transfers
> 
> Headers:		X-Request-ID=deea99ed-58c6-40b4-a972-0187e88bedbe
> 				Date=Fri, 14 Aug 2020 19:29:02 IST
> 				PSU-IP-Address=192.168.8.108
> 				Authorization=Bearer 919901d5-b7bc-34dd-b3e6-211ae10b017e
> 				PSU-ID=admin@wso2.com@carbon.super
> 				PSU-ID-Type=email
> 				Accept=*/*
> 				
> Body:
> {
>     "batchBookingPreferred": true,
>     "debtorAccount": {
>         **"bban": "5390 0754 7034"**
>     },
>     "requestedExecutionDate": "2020-08-19",
>     "payments": [
>         {
>             "instructedAmount": {
>                 "currency": "EUR",
>                 "amount": "23.50"
>             },
>             "debtorAccount": {
>                 **"bban": "5390 0754 7034"**
>             },
>             "creditorName": "Merchant123",
>             "creditorAccount": {
>                 "bban": "5390 0754 7034"
>             },
>             "remittanceInformationUnstructured": "Ref Number Merchant"
>         },
>         {
>             "instructedAmount": {
>                 "currency": "EUR",
>                 "amount": "23.50"
>             },
>             "debtorAccount": {
>                 **"bban": "5390 0754 7034"**
>             },
>             "creditorName": "Merchant123",
>             "creditorAccount": {
>                 "bban": "5390 0754 7034"
>             },
>             "remittanceInformationUnstructured": "Ref Number Merchant"
>         }
>     ]
> }

Automation Script Id: TC0401023

**Related Issues:**

**Comment by Akila94** [comment]
This test is verified as passing in the latest implementation. Hence, closing this issue.
